Feature/#92
bookmaru/MARU-iOS pull request #107
Opened 2021-09-14 07:40 UTC by psychehose

## 종류
- [ ] New Feature
- [x] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요
퀴즈 생성 뷰 & 로직
## 변경 사항

## 참고 사항
아직 화면전환을 붙이지 않았음. 뷰랑 로직만 봐주세요.

2021-09-14 08:00 UTC, 5anniversary requested changes

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Network/Model/DTO/MakeGroup.swift
> +  let makeGroup: Int
post와 get은 무엇인가요

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Network/MoyaNetworkLogger.swift
> +      print("ASDASD", result)
로그 지워주세요

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/Cell/BookContentCell.swift
> +  let oneLineTextView = UITextView()
이거는 fileprivate로 걸어주고 

```swift

extension Reactive where Base: BookContentCell {
   var changeText: Observable<String> {
      return base.oneLineTextView.rx.didChange
           .map { base.oneLineTextView.rx.text }
           .asObservable()
   }
}
```
로 해주는게 바깥에서 더 깔끔하게 보일듯 합니다!

바깥에서 쓰는 방법은 
```swift 
cell.rx.changeText
.bind(to: ~~)
혹을
cell.rx.chageText
.subscribe(onNext: ~~~
```

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/Cell/CreateQuizCell.swift
> +import RxCocoa
알파벳순으로... ㅎ...

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/Cell/CreateQuizCell.swift
> +}
이렇게 해주면 Action이 전역으로 사용되서 안좋을거같아요!

QuizAction이라던지 CreateQuizCell 안으로 옮겨주는게 좋을듯합니다.

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/Cell/CreateQuizCell.swift
> +class CreateQuizCell: UITableViewCell {
final 붙여주세요

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/Cell/CreateQuizCell.swift
> +  let xButton = UIButton()
요것도 BookContentCell의 review와 동일하게 해주는게 좋을거같아요!

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/Cell/CreateQuizCell.swift
> +  }
사용하지 않으면 제거 🙏

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
> +    KeychainHandler.shared.accessToken = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjMzMjcyMzU3fQ.Az8sUq84buQSXK5y3jrXSiA6DybdAKZge-iz0Tzr-2M"
제거 plz

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
>    }
요 init은 생명주기 함수 위에 올려주세요

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
> +  }()
요 헤더뷰는 헤더뷰 메소드 안으로 들어가도 좋을듯합니다!

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
> +    ])
이거 통일 시켜주세요!
그리고 네비바를 안사용하는거같은데 네비게이션 컨트롤러를 사용하는게 좋을거 같아요~~ ( 같은게 아니라 해주세요~ )

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
> +              for: indexPath) as? BookContentCell else { return UITableViewCell() }
```swift
guard let cell = tableView.dequeueReusableCell(
               withIdentifier: BookContentCell.reuseIdentifier,
               for: indexPath
) as? BookContentCell else { return UITableViewCell() }
```

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
> +    cellForRowAt indexPath: IndexPath) -> UITableViewCell {
```swift
  func tableView(
     _ tableView: UITableView,
     cellForRowAt indexPath: IndexPath
) -> UITableViewCell {
```

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
> +              for: indexPath) as? CreateQuizCell else { return UITableViewCell() }
```swift
      guard let cell = tableView.dequeueReusableCell(
               withIdentifier: CreateQuizCell.reuseIdentifier,
               for: indexPath
) as? CreateQuizCell else { return UITableViewCell() }
```

2021-09-14 08:00 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/ViewModel/CreateQuizViewModel.swift
> +      .asDriver(onErrorJustReturn: ())
void 처리를 할거면 map { $0 } 는 필요없어보입니다!

2021-09-15 01:15 UTC, psychehose commented on MARU/MARU/Network/Model/DTO/MakeGroup.swift
> +  let makeGroup: Int
잘못된 표현 GET, POST가 아니라 리퀘스ㅡㅌ 바디랑 리스폰스 바디라고 적었어야 했는데

2021-09-15 01:25 UTC, psychehose commented on MARU/MARU/Screens/Quiz/View/Cell/BookContentCell.swift
> +  let oneLineTextView = UITextView()
오 확실히 더 나은 방법이네 ㄱㅅㄱㅅ

2021-09-15 21:46 UTC, psychehose commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
> +    ])
뷰에서 새로운 뷰로 전환되어서 화면전환할 때 모달로 넣는 게 나을 거 같아서 네비게이션 바 일부러 사용 안했어

2021-09-15 21:48 UTC, psychehose commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
> +    ])
나는 '모임열기' 를 눌렀을 때 네비게이션 push보다 present가 나오는 게 더 맞다고 생각해서 이거는 의견이 갈릴 수 있는 거 같은데 일반적으로 어떻게 하려나

2021-09-15 21:52 UTC, psychehose commented on MARU/MARU/Screens/Quiz/ViewModel/CreateQuizViewModel.swift
> +      .asDriver(onErrorJustReturn: ())
아 여기서 화면전환을 할건데, 필요할 거 같아서 일단 map 찍어놓은 것인데 Mark도 달아놓을게.
화면전환 하면서 지울게

2021-09-16 02:32 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
> +    ])
흠... present는 맞는데 버튼들이 네비게이션 컨트롤러에 네비게이션 아이템으로 있었으면 좋겠다는 얘기였어 ㅎㅇㅎ

2021-09-16 02:32 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/ViewModel/CreateQuizViewModel.swift
> +      .asDriver(onErrorJustReturn: ())
👍

2021-09-16 06:39 UTC, psychehose commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
> +    ])
너가 의미하는 바가
let targetVC = UINavigationController(rootVC: ~~~)
view.present(targetVC) 이거야?

혹시 네베게이션 컨트롤러로 관리 해야만 하는 이유가 있을까? 퀴즈 생성 하면 어차피 dismiss 되고 메인화면이나 채팅화면으로 갈텐데

2021-09-16 11:27 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
> +    ])
흠... 버튼이 네비게이션 컨트롤러 위에 있는걸로 인식이 되니깐?!

네비게이션의 아이템이랑 동일하게 처리가 되면 상관이 없을텐데

내가 시뮬레이터에 빌드 돌려보니까 버튼 크기도 유동적인거 같구, 코드도 좀 더 복잡해지는 느낌이 있어

2021-09-16 11:31 UTC, 5anniversary commented
그리고 보통 회사에서는 리졸브는 어사이니 당사자가 아니라 코멘트 단 사람이 해. 그리구 수정이 되면 
![스크린샷 2021-09-16 오후 8 30 09](https://user-images.githubusercontent.com/22820675/133604514-0980264e-c150-4e80-916b-2cf0c80ef082.png)
여기 리뷰어 옆에 원형 버튼 누르면, 다시 검토해달라고. 리뷰 요청을 주는거니깐 다음부터는 그렇게 해줘!

2021-09-16 13:56 UTC, psychehose commented on MARU/MARU/Screens/Quiz/View/CreateQuizViewController.swift
> +    ])
okay

2021-09-16 16:28 UTC, merged