Feature/#112
bookmaru/MARU-iOS pull request #119
Opened 2021-09-22 16:24 UTC by profitjean

## 종류
- [ ] New Feature
- [x] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요
- 모임하고 싶은 책 검색 결과 화면 만듬
- 최근검색어 저장
- 팝업 화면 생성

## 참고 사항
- 필요한 이미지 추가
- 팝업 화면 더 생성 작업 들어가야함
- 팝업 화면 연결 진행하겠음

2021-09-22 16:28 UTC, 5anniversary commented
40개...?!

2021-09-22 16:32 UTC, profitjean commented
하하...🥲 천천히 봐주셔도 됩니다

2021-09-22 17:01 UTC, 5anniversary requested changes
린트 코멘트는...이제 네버...제발 잘 맞춰서 올려주세요. 
린트는 너무 시간적인 소비가 크네요...
제가 컴파일러가 아니라 중간중간에 못 발견하는것도 있을텐데...

잘 챙겨주셨으면 좋겠습니다. plz

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Profile/View/ProfileChangeViewController.swift
메소드 private

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateViewController.swift
>      self.dismiss(animated: true, completion: nil)
self 키워드 제거

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateViewController.swift
>    @objc func submitButtonDidTap() {
private 메소드

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/BookAlertViewController.swift
> +    }).disposed(by:disposeBag)
bind에 메소드에 들어가야할거같아요

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/BookAlertViewController.swift
> +    stateLabel.text = subGuideText
린트가 안맞는듯 합니다.

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/BookAlertViewController.swift
> +  let disposeBag = DisposeBag()
private

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +    let keyword: String?
요 keyword의 경우에는 init(keyword: String)으로 해서 init메소드 안으로 넣어주면 될거같아요!

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +    let keyword: String?
ViewModel이 꼭 ViewController 전역적으로 사용될필요는 없어요, 그래서 한번에 설정되는 화면이라면 ViewModel에
private로 넣어줘도 좋을거같습니다.

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +    let tapTextField: Driver<Void>
드라이버는 output으로 빼줄때...

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +    let tapTextField: Driver<Void>
Driver를 쓰는 이유를 생각해보면 메인 스레드에서 사용하기 위해서 사용하는건데 ViewModel 로직에서는 메인스레드에서 꼭 돌아야할필요는 없습니다.
output으로 빼줄때만 asDriver로 바꿔주세요

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +      }
이런의 경우에는 compactMap을 사용해주면 더 좋습니다!

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +        NetworkService.shared.search.bookSearch(queryString: input.keyword ?? "", page: 1) }
여기서도 keyword자체를 ViewModel에 올려주면 옵셔널일 경우가 없으니 처리가 간편해지겠죠?!

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +import RxCocoa
알파벳 순... 다른곳들도 기본 import와 라이브러리 import 잘 챙겨줬으면 좋겠네여...

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +    }
이런경우에는 else { return } 한줄로 작성해주세요

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +      .asDriver()
이런식으로 그냥 viewcontroller에서 누른것만 받아올때는 ViewModel을 거쳐주는게 좋은 로직일까요?! 
만약 맞다 생각하면 Driver로 받아준 코드를 다시 asDriver로 만들어주는게 이해가 안되네요

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/View/MyLibraryViewController.swift
> +        self.present(viewController, animated: true, completion: nil)
어디는 drive 어디는 subscribe 어디는 bind인데 역할에 따라서 명확하게 작성해줬음 좋겠습니다.

여기서도 self 키워드를 쓰기 위해서는 [weak self] 가 들어가야 할거같은데 없네요

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +    )
asDriver에 대해서는 ViewModel에서 잘 설명이 되었다고 생각합니다.

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +      .disposed(by: disposeBag)
여기에 load라는 이름은 명확하지 않은거 같습니다.
게다가 달러사인을 써줘서 더 어떤거인지 모르겠어요.
그리고 forEach에서도 달러사인을 쓸수있는데 왜 안서준거죠?! 오히려 반복문에서 달러사인이 들어가는게 더 정확한거 같아요

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
>    func render() {
private

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +import RxCocoa
알파벳순

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/MyLibraryHeaderView.swift
>    static let registerId = "headerView"
여기 identifier가 이미 있을텐데 추가 설정해준 이유가 무엇이죠~

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Network/Model/DAO/ResultBookCell.swift
> +    }
요 메소드는 어디에서 사용하는거일까요?! 
이런 메소드는 좋아보이지 않습니다.

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ResultBookViewController.swift
> +    activatorView.isHidden = false
이게 render 메소드에 들어가는게 맞을까요?! 메소드명과 일치하지 않는 역할이네요

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ResultBookViewController.swift
> +      make.top.equalTo(self.view.safeAreaLayoutGuide).offset(16)
이곳에서 self 키워드는 필요 없습니다.

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ResultBookViewController.swift
>    func setSearchBar() {
private

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
>    @objc func didTapCancelButton() {
private

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +  func bind() {
private

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +        self.navigationController?.pushViewController(resultSearchViewController, animated: false)
resultSearchViewController.transferKeyword 요 메소드가 여기에서 불리는게 좋은 방식일까요?!
각자 ViewController에서 불러주는게 맞다고 생각합니다. 

ViewController init에 keyword를 넘겨주고 해당 메소드 여기에서는 지워주세요

2021-09-22 17:01 UTC, 5anniversary commented on MARU/MARU/Network/Model/DAO/ResultBookCell.swift
> +        bookImageView.image = Image.group1029
model에 imageURL로 변경해주시구요 아래에 else 로 해줘야 제대로 적용이 될거같이 보입니다.

!= "" 일때 imageFromURL을 해주고 아래에서 덮어 씌워주는거 같은데...

그리고 하면서 imageFromURL로 변경해주세요

else 문이나 

guard 문으로 해주는게 깔끔할듯 하네요

2021-09-22 17:12 UTC, psychehose commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +    )
이게 무슨 뜻이죠~_~

2021-09-23 16:31 UTC, profitjean commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +    let keyword: String?
저기 struct Input 안에 init(keyword: String) { } 쓰는거 맞나요? 
그렇게 해봤는데 나머지 Input 요소들도 init해줘야한다고 오류가 우당탕탕..

2021-09-23 16:38 UTC, profitjean commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +      .asDriver()
그럼 이거 cancel이나 reSearch는 뷰컨트롤러에서 해당버튼.rx.tap.subscribe ~ 이런식으로 하는게 나을까요?
Driver 아예 빼버리고

2021-09-23 17:06 UTC, psychehose commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +      .asDriver()
누른 것만 받아올 때도 일관성 때문에 뷰모델 거치는 게 좋지 않을까?

2021-09-23 17:08 UTC, psychehose commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +    let keyword: String?
나는 input에 Driver<String>을 사용하긴 했음

2021-09-23 17:14 UTC, psychehose commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +    let keyword: String?
아 나도 이렇게 짰구나
만약 내가 수정한다면, 
viewModel에서

init(keyword: String) {
self.keyword = keyword
}
해 놓고 
viewController에서, private let viewModel = ViewModel(keyword = keyword) 로 수정할 거 같아

2021-09-23 17:15 UTC, psychehose commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +    )
그냥 Observable로 바꾸라는 뜻인가보다

2021-09-23 17:26 UTC, psychehose commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +      .disposed(by: disposeBag)
변수이름은 워낙 내가 대충 지어서 쏘리

이거 왜 이렇게 했냐면 Realm에서 query 사용하려고 Results<RecentKeyword> ( Result의 배열) 이렇게 아웃풋으로 내보내주는데
검색한 순서로 stack을 쌓아주려다보니까 검색한 시간을 넣었어. 

그래서 저기 $0 표시는 Results고 안에 있는 recentKeyword는 Result 입니다.

2021-09-23 17:29 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +      .asDriver()
흠...그렇게 따지면 그럴수있겠네... 그럼 킵!
이건 선호도의 문제인거같아

2021-09-23 17:30 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ViewModel/ResultBookViewModel.swift
> +    let keyword: String?
init에서 해주기 그렇다면 keyword에 옵셔널을 빼주는게 좋을거같아 어찌됐든 ""이나 nil 아닌 상태로 넘어오는거는 확실하니까

2021-09-23 17:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +    )
네넹!! Driver 키워드 자체가 메인 스레드에서만 강제한다는 건데(목적은 UI로직이 다 메인스레드에서만 실행시킬수있으니깐)
ViewModel 로직을 거기에 넣을 필요는 없다?! 생각해
백그라운드에서 동시에 실행될수도 있으니까

2021-09-23 18:11 UTC, psychehose commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +    )
I got it

2021-09-24 06:44 UTC, profitjean commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +      .disposed(by: disposeBag)
일단 load말고 save로 바꿔봤슴!
검색어 입력하면 원래 최근검색어 리스트에 append되는거라 이름을 이렇게 바꾸었습니다. 별로면 말해주삼..
달러사인 고민을 해봤는데 위에서 세호가 말한대로 Realm쪽 데이터라 뭐로 대체하면 좋을지 좀 더 생각을 해봐야할 것 같슴니다

2021-09-24 08:32 UTC, psychehose commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +      .disposed(by: disposeBag)
내가 바꾼다면 내 생각에는 local DB에서 가져와서 output으로 내보내기 때문에  save 보단 load가 맞는 거 같고 의미를 명확하게 하려고 하면 loadRecentKeywords로 할 거 같아 
@profitjean

2021-09-24 08:36 UTC, profitjean commented on MARU/MARU/Screens/Library/SearchBookViewController.swift
> +      .disposed(by: disposeBag)
의미는 loadRecentKeywords가 완전 정확하긴 한데, 너무 길지 않나 싶어...? 그럼 그냥 load로 가는게 맞을 것 같아

2021-09-25 06:04 UTC, 5anniversary approved these changes

2021-09-25 07:45 UTC, merged