Feature/#124
bookmaru/MARU-iOS pull request #128
Opened 2021-09-27 12:55 UTC by profitjean

## 종류
- [x] New Feature
- [x] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요
- 팝업화면을 만들었어요 (평가 제한 팝업뷰_하나 남았던 화면)

## 변경 사항

## 참고 사항
- 서재 추가하기 팝업 버튼 눌렀을 때 나오게 하려고 했는데 안됌.서버 통신 붙이면서 수정을 해봐야합니다

2021-09-27 13:07 UTC, 5anniversary requested changes

2021-09-27 13:07 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +  var isLeader: Bool?
요거는 왜 cell 안에 새로운 값으로 넣어준거인가요~

2021-09-27 13:07 UTC, 5anniversary commented on MARU/MARU/Screens/Library/ResultBookViewController.swift
> +              "성공적으로 서재에 담겼습니다.")
"성공적으로 서재에 담겼습니다."
)
개행 넣어주세요~

2021-09-27 13:07 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +  var isLeader: Bool?
제 말은 cell.evaluateButton.isHidden = false과 ViewContoller만 바깥으로 나가다 보니깐
map을 써줘서 처리했으면 좋겠다는 의도로 작성한거였어요!

```swift
return base.evaluateButton.rx.tap
      .map { _ -> UIViewController in
          if base.data?.isLeader {
             return OOOViewController
          }
          return OOOViewController
      }
      .asObservable()
```

2021-09-27 13:07 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/ResultBookCell.swift
> +  var addBookButton = UIButton().then {
fileprivate로 처리해줘야 extension Reactive로 빼줄수가 있습니다!

2021-09-27 13:07 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/BookAlertViewController.swift
> +  // 모임개수 초과 경고 이미지도 넣기
Todo 인가요?!

2021-09-27 13:07 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateWarningViewController.swift
> +    // 11~15
이건 무슨 주석인가요?!

2021-09-27 13:07 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateWarningViewController.swift
> +  @objc func didTapSubmitButton() {
private 함수로 설ㅈ어해주세요~

2021-09-27 13:07 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateWarningViewController.swift
> +      make.trailing.equalToSuperview()
make.leading.trailing.bottom.equalToSuperview()
로 변경해주세요

2021-09-27 13:07 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateWarningViewController.swift
> +      make.centerX.equalTo(popUpView)
x값이 중복 설정되는듯 한데 확인 다시 한번 해주세요

2021-09-27 13:07 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateWarningViewController.swift
> +      make.leading.equalTo(popUpView).offset(56)
여기서도 x값이 중복 설정이 되는듯 합니다.

2021-09-27 13:08 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/BookAlertViewController.swift
> +  // 모임개수 초과 경고 이미지도 넣기
주석은 본인만 보기 위한게 아니기 때문에 어떤거인지 정확하게 알려주세요!

2021-09-27 13:11 UTC, profitjean commented on MARU/MARU/Screens/Popup/BookAlertViewController.swift
> +  // 모임개수 초과 경고 이미지도 넣기
마크마크 이미지 init으로 넣어줘서 팝업 용도 바꾸려고...어서 바꿔놓겠습니다

2021-09-27 13:12 UTC, profitjean commented on MARU/MARU/Screens/Popup/EvaluateWarningViewController.swift
> +    // 11~15
아 이거는 진짜 의미없는 주석..지우겠습니다

2021-09-27 13:13 UTC, profitjean commented on MARU/MARU/Screens/Popup/BookAlertViewController.swift
> +  // 모임개수 초과 경고 이미지도 넣기
그니까 미리 저렇게 적어놓고, 나중에 서버연결할때 이미지 이름 적용하기 편하려고 미리 적어놓은 내용입니다!

2021-09-27 13:15 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/BookAlertViewController.swift
> +  // 모임개수 초과 경고 이미지도 넣기
👌

2021-09-27 14:19 UTC, profitjean commented on MARU/MARU/Screens/Library/Cell/ResultBookCell.swift
> +  var addBookButton = UIButton().then {
하하 변경해고 익스텐션으로 빼서도 해봤는데 왜 안먹힐까나요 ~~ ㅠㅠㅠ...

2021-09-27 14:21 UTC, profitjean commented
리뷰 사항 반영 완료🙌

2021-09-27 14:28 UTC, 5anniversary approved these changes

2021-09-27 14:28 UTC, 5anniversary commented
주석은 나중에 지우는건가요?!

2021-09-27 16:35 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/ResultBookCell.swift
> +  var addBookButton = UIButton().then {
흠 나중에 하는걸로...

2021-09-28 10:34 UTC, profitjean commented
당연하지요 서버 연결 작업끝내면 바로 지울 것.

2021-09-28 10:36 UTC, merged