Feature/#129
bookmaru/MARU-iOS pull request #131
Opened 2021-10-04 07:12 UTC by profitjean

## 종류
- [x] New Feature
- [X] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요
- 모임 입장 화면 서버 연결 진행 (JoinViewController)
- 🚑*_서버 연결은 됐는데 bind부분에서 데이터가 nil값으로 넘어감..이 부분 해결해야함_

## 참고 사항
- 메인화면에서 지금새로나온모임 Cell 클릭하고 나오는 화면이 JoinVC

2021-10-04 07:24 UTC, 5anniversary requested changes
bind 부분에서 nil이 날아온다는게 어떤건가요?!

2021-10-04 07:24 UTC, 5anniversary commented on MARU/MARU/Network/Model/DTO/GroupInformation.swift
> +  let classes: JSONNull?
이건 뭔가요~

2021-10-04 07:24 UTC, 5anniversary commented on MARU/MARU/Network/Model/DTO/GroupInformation.swift
> +    }
hashValue, equatable 사용이 알맞지 않은거같은데...요?!

2021-10-04 07:28 UTC, profitjean commented on MARU/MARU/Network/Model/DTO/GroupInformation.swift
> +  let classes: JSONNull?
저 classes 부분이 그냥 null로 날라오는거라서 (서버 위키에 사용되지 않는 컬럼이라고 표기되어있고 null로 받아와짐 ) 데이터짜주는 quicktype 사이트 사용해서 돌려보니 JSONNull로 해야한다고 하더라고요,,그래서 hashvalue, equatable도 사용하게 된 것입니다.

2021-10-04 07:29 UTC, profitjean commented
nil이 날라온다는건 xcode로그창에는 200으로 데이터가 잘 넘어와지는데 bind 함수내에서 확인할때는 nil로 뜬다는 말이었습니다

2021-10-04 07:32 UTC, 5anniversary commented on MARU/MARU/Network/Model/DTO/GroupInformation.swift
> +  let classes: JSONNull?
음... 그렇다면 백엔드에서 어떤 데이터가 날아오는지 알려달라 하는게 먼저인거같구요!

null로만 날아온다면 안넣어줘도 상관은 없습니다~ 호호...

2021-10-04 07:37 UTC, profitjean commented on MARU/MARU/Network/Model/DTO/GroupInformation.swift
> +  let classes: JSONNull?
그럼 서버한테 물어보고 오늘안으로 반영해놓겠습니다 ~~~

2021-10-04 07:38 UTC, 5anniversary commented on MARU/MARU/Network/Model/DTO/GroupInformation.swift
> +  let classes: JSONNull?
👍

2021-10-05 15:12 UTC, profitjean commented
해결 완료했습니다 재리뷰 부탁드립니다 @5anniversary

2021-10-05 15:15 UTC, 5anniversary approved these changes
지금 코멘트는 다음 PR에서 수정해도 됩니다~

2021-10-05 15:15 UTC, 5anniversary commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +//    $0.attributedText = attributedString
이거 사용안하는거면 지워주세요~

2021-10-05 15:15 UTC, 5anniversary commented
go merge

2021-10-05 15:41 UTC, merged