Feature/#151
bookmaru/MARU-iOS pull request #152
Opened 2021-10-20 07:47 UTC by profitjean

## 종류
- [x] New Feature
- [ ] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요
- 방장 평가 서버 연결중
- 나의 서재 화면 동시에 고칠부분 고치는중
## 변경 사항

## 참고 사항
- 나의 서재 - 담아둔 모임 화면 데이터가 안받아와짐 (PastMeetingVC/PastMeetingViewModel)

2021-10-20 07:53 UTC, 5anniversary requested changes
안받아와짐 이라고 작성이 되어있으면 알기가...힘듭니다...

어디서부터 안받아와지는지 network 서비스가 호출은 되는지 호출이 되서 디코드가 되는지 안되는지를 먼저 알려주세요

2021-10-20 07:53 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +      bookImageView.imageFromUrl(data?.image, defaultImgPath: "")
이거 image로 변경해주세요

2021-10-20 07:53 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +      bookImageView.imageFromUrl(data?.image, defaultImgPath: "")
.image(~~

2021-10-20 07:57 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +      bookImageView.imageFromUrl(data?.image, defaultImgPath: "")
http://aladin.kr/p/5WuCM

2021-10-20 09:04 UTC, profitjean commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +      bookImageView.imageFromUrl(data?.image, defaultImgPath: "")
참고사항에 말을 모호하게 써놨네요 죄송합니다. viewmodel 쪽에서 flatmap으로 받아온 이후  map으로 받아오는 부분에서 nil로 받아와지더라고요 (breakpoint 걸어서 확인..)

2021-10-20 09:05 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +      bookImageView.imageFromUrl(data?.image, defaultImgPath: "")
그렇게 된다면 moya logger에서는 나오는 중인가요?!

2021-10-20 09:06 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +      bookImageView.imageFromUrl(data?.image, defaultImgPath: "")
logger true로 해주고 나오는지 확인해주세여 🙏

2021-10-20 09:06 UTC, profitjean commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +      bookImageView.imageFromUrl(data?.image, defaultImgPath: "")
yes..200으로 받아와지는중

2021-10-20 09:06 UTC, profitjean commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +      bookImageView.imageFromUrl(data?.image, defaultImgPath: "")
책은..추천하시는건가요..읽어보라고..

2021-10-20 09:06 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +      bookImageView.imageFromUrl(data?.image, defaultImgPath: "")
200말고 response 데이터가 있는지 없는지가 궁금합니다

2021-10-20 09:07 UTC, profitjean commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +      bookImageView.imageFromUrl(data?.image, defaultImgPath: "")
옙 data 뜨고 있어여 나의서재 화면에서 쓰는 api 똑같은거 쓰는거라

2021-10-20 09:09 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
> +      bookImageView.imageFromUrl(data?.image, defaultImgPath: "")
data가 잘 날아오고 있다면 해당 데이터를 model로 파싱하는 구조가 제대로 되어있는지 확인해주세요

try로 decode하는게 아니라 에러가 안나는 상황일수도 있습니다.

2021-10-21 01:44 UTC, 5anniversary commented
요거 수정 완료되면 아래 리뷰어 버튼 다시 눌러주시구요, 어사이니도 걸어주세요

![스크린샷 2021-10-21 오전 10 44 14](https://user-images.githubusercontent.com/22820675/138196848-b622f6ea-8bac-4d96-8b69-44c088721839.png)

2021-10-21 02:26 UTC, profitjean commented
서버 연결은 끝났는데, 화면 조금 수정할게 남아있어서 그부분 수정하고 다시 리뷰요청 누르겠슴니다.

2021-10-21 02:27 UTC, profitjean commented
아냐 아직 리뷰 요청한거 아닌데 왜 지혼자 되는거야..요청한거 아님 아직 리뷰하지마아..아직 안고쳤어요..엉엉..

2021-10-21 08:51 UTC, profitjean commented
@5anniversary ~리뷰요청다시걸기~

2021-10-21 23:32 UTC, 5anniversary requested changes

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Network/Service/GroupService.swift
> +  // /api/v2/group/1/leader/1?score=4.5
이 주석은 무슨 용도인가요?!

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/LibraryDiaryCell.swift
> +      bookImageView.imageFromUrl(data.bookImage, defaultImgPath: "")
imageFromURL은 이제부터 없는 메소드입니다 image 메소드를 사용해주세요

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/MyBookCaseCell.swift
> +    $0.backgroundColor = .none
none으로 지정한 이유는 무엇인가요?!

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/MyBookCaseCell.swift
> +  }
private를 안쓴이유는?!

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/MyBookCaseCell.swift
>      cell.rx.binder.onNext(bookData?.imageURL ?? "")
여기 인덴트가 안들어간듯 싶습니다.

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/MyBookCaseCell.swift
> +    cell.awakeFromNib()
collectionView에는 awakeFromNib이라는 메소드를 사용하지 않습니다. 🙏 

[참고](https://jinnify.tistory.com/58)

awakeFromNib 메소드는 적절치 않습니다.

init메소드에서 해결해주세요

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/MyBookCaseCell.swift
> +    } else {
guard 문을 이용해주세요 `guard boodData != nil else { return }`

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/MyBookCaseCell.swift
>    }
else는 return 이 가능할때는 사용하지 않는게 좋습니다.

코드를 읽을때 오히려 생각이 많아집니다. 

학교에서 배우게 될때는

~~~swift
if OO == 1 {
    return 1
} else if OO == 2 {
    return 2
} else {
    return 3
} 
~~~

이 되는데 

~~~swift
if OO == 1 {
    return 1
} 
if OO == 2 {
   return 2
} 
return 3 
~~~
이렇게 해결하면 사람의 생각으로 이해하기 더 편해집니다 (else는 위에 if문도 읽어야하기 때문이죠)

else는 어쩔수없는 경우에만!

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/MyLibraryCell.swift
>    }
여기는 private이 없는 이유는 뭔가요?!

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/MyLibraryCell.swift
>      $0.backgroundColor = .none
여기도 backgroundColor = .none을 지정한 이유는 뭔가요?

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/MyLibraryCell.swift
> +        $0.bottom.equalTo(self.contentView).offset(-3)
이런 경우에는

`$0.edges.equalToSuperView().inset(UIEdgeInsets(leading: 3, top: 3, trailing: -3, ~~~)`
으로 해결할 수 있을듯 싶네요

안에 세부 데이터는 대충 적었습니다.

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/MyLibraryCell.swift
> +    return 1
~~~swift
   (
 OOO,
 OOO
) -> OOO {
~~~

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Cell/PastMeetingCell.swift
>    }
여기에 초기화 코드가 들어가야할듯 싶습니다.

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Model/Library.swift
> +      }
else 문 지우기

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/Model/Library.swift
> +      if data.bookcase.count == 0 {
data.bookcase.isEmpty를 사용해도 좋을듯 싶어요

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/View/MyLibraryViewController.swift
>      // MARK: - 모임하고 싶은 책
이렇게 셀 안의 프로퍼티를 viewcontroller에서 처리해주는게 좋지 않습니다...

분명한 이름의 메소드를 만들어서 처리해주세요

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/View/MyLibraryViewController.swift
> +      }
위와 동일하게, print문 지우기

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Library/View/MyLibraryViewController.swift
> +      if data.bookcase.count == 0 {
isEmpty

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateViewController.swift
> +  var score: Int?
private가 붙은거랑 아닌거의 차이는 무엇인가요?

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateViewController.swift
>    let disposeBag = DisposeBag()
여기도 딱히 안붙을 이유는 없는듯 싶은데 무엇인가요?!

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateViewController.swift
> +        else { return (groupID: -1, leaderID: -1, score: -1)}
` else { return (groupID: -1, leaderID: -1, score: -1) }`
맨 뒤에 한칸 넣어주세요

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateViewController.swift
> +        presentingVC?.navigationController?.popViewController(animated: true)
여기 presentingVC 인덴트가 안들어간듯 싶습니다.

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateViewController.swift
> +        }
요거는 에러 메시지를 보여주고 pop시켜주는거라 그런건가요?!

2021-10-21 23:32 UTC, 5anniversary commented on MARU/MARU/Screens/Popup/EvaluateViewModel.swift
> +  // groupID, leaderID, score
필요한 주석인가요?!

2021-10-21 23:32 UTC, 5anniversary commented
💪

2021-10-29 15:44 UTC, psychehose approved these changes

2021-10-30 16:56 UTC, 5anniversary commented
내일... PR에서 다른 커밋을 빼보아요...

2021-10-31 04:35 UTC, merged