Feature/#reset
bookmaru/MARU-iOS pull request #180
Opened 2021-12-20 11:14 UTC by profitjean

## 종류
- [v] New Feature
- [ ] Change
- [v] Bug fix
- [ ] Setup (CI / CD)

## 개요
- 지난주까지 계속 고쳐오던 qa부분들 반영합니다.

2021-12-20 11:14 UTC, profitjean commented
@psychehose

2021-12-21 23:09 UTC, psychehose reviewed
고생했다!

2021-12-21 23:09 UTC, psychehose commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +      .disposed(by: disposeBag)
코드 살짝 보니까 output.data가 있는 걸로 봐서 viewmodel에서 이 로직을 처리하는 방법도 있을 거 같아.

2021-12-21 23:09 UTC, psychehose commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +      .disposed(by: disposeBag)
P.S: 다시 작성 했으면 좋겠다는 말 아님

2021-12-21 23:09 UTC, psychehose commented on MARU/MARU/Screens/Library/BookFavoritesViewController.swift
> +        }
나도 요즘 코딩하면서 느낀건데 내가 mvvm 적용할 때 
 vm에서 처리할 수 있는 것을  vc까지 끌고와서 하서 처리를 하는 거 같은 느낌을 많이 받았어.
옳은 방법인지는 솔직히 모르겠는데.

output.isHiddenFlag.drive(emptyView.rx.isHidden) 과 같은 방식으로 최대한 하려고 노력하는 중.

2021-12-21 23:09 UTC, psychehose commented on MARU/MARU/Screens/Library/BookFavoritesViewController.swift
> +
👍👍

2021-12-21 23:09 UTC, psychehose commented on MARU/MARU/Screens/Library/BookFavoritesViewController.swift
> +
presentationStyle에서 .overCurrentContext가 뭐인지 알 수 있을까?

2021-12-21 23:10 UTC, psychehose approved these changes

2021-12-22 02:29 UTC, 5anniversary requested changes
리뷰 항목 확인 plz

2021-12-22 02:29 UTC, 5anniversary commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +        }
```suggestion
        if self.data?.groups?.isFailedGroupQuiz == false && self.data?.groups?.canJoinGroup == true {
          let viewController = QuizViewController(groupID: self.groupID)
          viewController.modalPresentationStyle = .fullScreen
          self.present(viewController, animated: true, completion: nil)
          return
        }
        self.showToast("참여가 불가한 토론방입니다.")
```

한칸씩만 띄어주시죠 :호호:

2021-12-22 02:29 UTC, 5anniversary commented on MARU/MARU/Screens/Library/BookFavoritesViewController.swift
> +    return 1
```suggestion
    guard let count = data?.bookcase.count else { return 1 }
    if count == 0 {
      return count / 3
    } 
    if count > 3 {
      return count + 1
    }
    return 1
```
좀 깔끔하게 보여지는 방법!

2021-12-22 02:29 UTC, 5anniversary commented on MARU/MARU/Screens/Library/BookFavoritesViewController.swift
> +        }
```suggestion
      .subscribe( onNext: { [weak self] _ in
        guard 
          let self = self,
          let bookcase = self.data?.bookcase[indexPath.item] 
        else { return }
        let viewController = CreateQuizViewController(
          bookModel: BookModel.init(
            isbn: bookcase.isbn,
            title: bookcase.isbn.title,
            author: bookcase.isbn.author,
            imageURL: bookcase.isbn.imageURL,
            category: bookcase.isbn.category,
            hasMyBookcase: true)
        )
        if bookcase..canMakeGroup == true {
          self.navigationController?.pushViewController(viewController, animated: true)
          return
        }
          // TODO: - 모임열수없음 팝업 추가
          let targetViewController = JoinLimitViewController()
          targetViewController.modalPresentationStyle = .overCurrentContext
          targetViewController.modalTransitionStyle = .crossDissolve
          self.present(targetViewController, animated: true)
```

여기도 이렇게 하면 좀 더 깔끔하게 짤수있을거같아요~

bookcase에 옵셔널인 항목을 모르기 때문에 확인 Plz

2021-12-22 02:30 UTC, 5anniversary commented
data안에 있는값을 하나하나 꺼내서 쓰기보다는 자주쓰는 값이면 한번에 꺼내서 써버리는게 좋습니다!!
더불어... optional 관리도 되고... :호호:

2021-12-26 07:10 UTC, profitjean commented on MARU/MARU/Screens/Library/BookFavoritesViewController.swift
> +
https://ios-development.tistory.com/206
종권아저씨가 친절하게 설명해주셨습니다 참고참고

2021-12-26 08:01 UTC, profitjean commented
리뷰 내용 반영했습니다 :)

2021-12-28 22:57 UTC, psychehose approved these changes
항상 RxSwift를 공부하면서 생각하는건데 collectionView or tableView의 dataSource에서 onNext 같은 걸 안쓰는 법이 있을까?

2021-12-28 22:57 UTC, psychehose commented on MARU/MARU/Global/Extensions/Array+.swift
> +}
이중 배열로 만드는 익스텐션이네 stride는 처음 봤는데 감사합니다.
import UIKit은 꼭 필수적인거야?

2021-12-29 13:52 UTC, 5anniversary commented
> 항상 RxSwift를 공부하면서 생각하는건데 collectionView or tableView의 dataSource에서 onNext 같은 걸 안쓰는 법이 있을까?

왜 안쓰려고 하는지 모르겠어

2021-12-30 04:05 UTC, 5anniversary approved these changes

2021-12-30 08:34 UTC, profitjean commented on MARU/MARU/Global/Extensions/Array+.swift
> +}
놉 아닙니다...!

2021-12-30 08:38 UTC, profitjean commented
> 항상 RxSwift를 공부하면서 생각하는건데 collectionView or tableView의 dataSource에서 onNext 같은 걸 안쓰는 법이 있을까?

onNext 없이 콜렉션뷰나 테이블뷰 cell에 데이터를 표현할 수 있을까? 어떻게 처리하고 싶었는지 생각이 궁금합니다 대충 아이디어라도..?

2021-12-30 13:38 UTC, profitjean commented
@5anniversary @psychehose 최종확인부탁부탁

2021-12-30 14:08 UTC, merged