프로필 변경, 모임 입장 제한 QA내역 반영
bookmaru/MARU-iOS pull request #186
Opened 2022-01-10 14:14 UTC by profitjean

## 종류
- [ ] New Feature
- [ ] Change
- [x] Bug fix
- [ ] Setup (CI / CD)

## 개요
2차 QA 내역에 있던 프로필 변경 문제와 모임 입장 제한 문제를 다시 해결했습니다
## 변경 사항
1. 프로필 변경 쪽에 닉네임과 이미지 UserDefault 다시 저장하게끔 설정했습니다.
2. 중복 닉네임 문제 해결완료!
3. 모임입장 제한 조건을 모두 설정해놓았습니다.
4. 두 화면 모두 상태별로 버튼 비활성화/활성화 처리 걸어두었습니다.
## 참고 사항
1. JoinViewController(모임입장화면) 쪽에서 
조건에 따라 버튼의 색깔을 파란색/회색으로 변경이 되도록 didSet에서 처리해놓았는데 
이게 맞는것인지요,,bind부분에 넣으려다 헤맸었습니다. 
이 부분은 나중에 다시 고쳐볼 수 있을 거 같아 mark주석처리 해두었습니다.

2022-01-10 14:15 UTC, profitjean commented
@psychehose

2022-01-12 01:37 UTC, 5anniversary commented
PR 이름 알맞게 변경해주세요 🙏

2022-01-12 01:40 UTC, 5anniversary commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +      }
data의 group만 사용하는거 같은데 guard로 빼내주면 좋을거같습니다.
옵셔널이라서 조금 그렇기도 하구요, if문이 이중으로 들어간것도인것도 조금 그렇습니다!

2022-01-12 01:44 UTC, 5anniversary requested changes

2022-01-12 01:44 UTC, 5anniversary commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +      make.bottom.equalTo(view)
요거 이렇게 되면 누르기 조금 힘들어지지 않나요?! 높이도 같이 변경이 되어야할거같은데...

2022-01-12 01:44 UTC, 5anniversary commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +          }
여기도 이중으로 if문 들어간것과 함께 let으로 빼는것도 좋은데 guard로 빼면 그냥 canJoinGroup, isFailedGroupQuiz Bool 형을 그대로 쓸수있기때문에 그렇게 해주셨으면... 합니다 🙏 

Bool 형을 굳이 한번 더 비교해줘야하나 생각이 들어서요...

2022-01-12 01:44 UTC, 5anniversary commented on MARU/MARU/Screens/Profile/View/ProfileChangeViewController.swift
>          if statusCode == 200 {
요거 || or로 201도 넣어주세요 🙏

2022-01-12 01:56 UTC, 5anniversary commented
이해가 어렵다면 얘기해주세요~!

2022-01-13 01:36 UTC, profitjean commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +      }
그쳐 저도 이중포문이 구려서..

2022-01-13 01:36 UTC, profitjean commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +      make.bottom.equalTo(view)
아 이부분 바꾼게 모임입장화면 입장버튼 bottom 쪽에 여백 생기는게 신경쓰여서 바꾼거에요.
테스트할때는 이상 없긴 했는데 height 쪽도 고정해볼게요

2022-01-13 01:36 UTC, profitjean commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +          }
> Bool 형을 굳이 한번 더 비교해줘야하나 생각이 들어서요...
>>
지금 코드에 있는 &&(AND)조건이 굳이 필요하다는 말씀이신건지요~~?
이 부분 말이 잘 이해가 안가서 좀 더 자세히 설명해주시면 감사하겠습니다

2022-01-13 01:36 UTC, profitjean commented on MARU/MARU/Screens/Profile/View/ProfileChangeViewController.swift
>          if statusCode == 200 {
옙~~

2022-01-15 16:48 UTC, profitjean commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +          }
이 부분 고쳤는데 확인부탁드립니다:)

2022-01-15 16:50 UTC, 5anniversary approved these changes
수고하셨습니다~

2022-01-15 16:50 UTC, 5anniversary commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +        return
오 이렇게 간단하게 해결이 되는건가요?! 👍

2022-01-15 16:50 UTC, 5anniversary commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +          )
요거 == true, == false 만 없애주면 좋을거같습니다.

2022-01-16 02:13 UTC, profitjean commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +        return
넵 두 가지 케이스만 제외하고 버튼색이 회색이라서  
guard else로 바꿔봤어요
이게 될까? 하고 실행해봤는데 잘되길래 저도 놀랬던,,ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 코드가 훨씬 간결해졌습니다

2022-01-16 02:14 UTC, profitjean commented on MARU/MARU/Screens/Join/View/JoinViewController.swift
> +          )
넵 지웠습니다~

2022-01-16 02:15 UTC, profitjean commented
머지해도 될까요?!

2022-01-16 02:20 UTC, 5anniversary commented
LGTM :)

2022-01-16 02:27 UTC, merged