Feature/#14
bookmaru/MARU-iOS pull request #19
Opened 2021-05-24 14:02 UTC by psychehose

## 종류
- [x] New Feature
- [x] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요
 MainViewController  UI 구성
## 변경 사항
새로 만듬
## 참고 사항
UICollectionCompositional layout 사용

2021-05-24 14:02 UTC, 5anniversary commented
- [x] New Feature
마크다운 형식은 - [x] 입니다~

2021-05-24 14:09 UTC, psychehose commented
> [x] New Feature
> 마크다운 형식은 - [x] 입니다~

넵

2021-05-25 01:37 UTC, 5anniversary requested changes

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Global/Extensions/UIView+.swift
> +  func applyQuizViewShadow() {
이 메소드 applyShadow로 처리 안되나요?? ㅎㅇㅎ

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Component/MaruSearchView.swift
> +  private func applyProperty() {
위에 퀴즈 shadow랑 무슨 차이인지 UIViewExtension에 있는 applyShadow 메소드를 안쓰고 또다른 메소드를 사용하는 이유를 모르겠습니다.

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Component/MaruSearchView.swift
> +  func enterTextField() {}
여기서도 왜 새로운 delegate를 만들어서 사용하는지 모르겠어요 데이터 전달하는데 사용을 한다?

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/Model/Book.swift
> +  var roomChief: String
제가 알기로는 다 변경 가능하지 않은데 왜 변수인지 모르겠어요~

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/Model/ViewMain.swift
> +  var roomChief: String
Book 구조체랑...똑같은데...?

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/MainHeaderCell.swift
> +  static let identifier = "MainHeaderView"
identifier 연결해놨어요~ static으로 추가해줄필요 없습니다. cell 안에는 기본적으로 reusableIdentifier가 있을거에요 안에 내용은 해당 클래스 명과 동일합니다

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/MainHeaderCell.swift
> +    backImageView.adds([mypageButton,
~~~swift
adds([
  mypageButton,
   ...
])
~~~
이렇게 개행 처리해주세요

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/MainHeaderCell.swift
> +      make.leading.equalTo(self.snp.leading).inset(16)
여긴 equalToSuperView 가 좋을거같아요~

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/MainHeaderCell.swift
> +      make.trailing.equalTo(self.snp.trailing)
여기는 equalToSuperView가 좋을거같아요

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/NewMeetingCell.swift
> +  static let identifier = "NewMeetingCell"
reusableIdentifer

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/NewMeetingCell.swift
> +    $0.image = UIImage(named: "qmarkLeft")
Image.qmarkLeft

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/NewMeetingCell.swift
> +    $0.image = UIImage(named: "qmarkRight")
Image.qmarkRight

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/NewMeetingCell.swift
> +    shadowView.adds([bookImageView,
여기도 개행처리

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/NewMeetingCell.swift
> +    explainBox.adds([bookMeetingExplainementLabel,
여기도 개행처리

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/NewMeetingCell.swift
> +  private func applyShadow() {
여기도 UIViewExtension에 있는 applyShadow

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/PopularMeetingCell.swift
> +  static let identifier = "PopularMeetingCell"
reusableIdentifier

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/PopularMeetingCell.swift
> +      $0.font = UIFont.systemFont(ofSize: 13, weight: UIFont.Weight.bold)
~~~swift
      $0.font = UIFont.systemFont(ofSize: 13, weight: .bold)
~~~

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/PopularMeetingCell.swift
> +      make.width.equalTo(contentView.snp.width)
contentView에 add하지 않았는데 contentView에 autoLayout 걸어써요 superView나 혹은 contentView로 정해주세요
저는 contentView 추천

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/MainViewController.swift
> +
여기 왜 개행?

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/MainViewController.swift
> +      guard let cell =
~~~swift
let cell: MainHeaderCell =  collectionView.deque(indexPath: indexPath)
~~~
아마 extension에 있을거에요 한줄로 간편하게~

2021-05-25 01:37 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/QuizViewController.swift
> +import RxRelay
RxCocoa안에 RxRelay가 있을텐데..?

2021-05-26 14:11 UTC, psychehose commented on MARU/MARU/Global/Extensions/UIView+.swift
> +  func applyQuizViewShadow() {
저거 익스텐션 적용이 안되서 만들었을거야 아마 어차피 퀴즈뷰 다시 만들어야하니까 지울게

2021-05-26 14:22 UTC, psychehose commented on MARU/MARU/Screens/Component/MaruSearchView.swift
> +  private func applyProperty() {
익스텐션에 있는 건 border width를 안만들어줘서 사용 안했었어요.그래서  addProperty에 applyshadw 넣는 걸로 수정

2021-05-26 14:24 UTC, psychehose commented on MARU/MARU/Screens/Component/MaruSearchView.swift
> +  func enterTextField() {}
사용 아직 안했어요. 커먼뷰로 만들었기 때문에 혹시 이용할 가능성이 높아서 그냥 만들어 놓은 것

2021-05-26 14:25 UTC, psychehose commented on MARU/MARU/Screens/Main/Model/Book.swift
> +  var roomChief: String
let으로 변경

2021-05-26 14:27 UTC, psychehose commented on MARU/MARU/Screens/Main/Model/ViewMain.swift
> +  var roomChief: String
Book은 서버에서 받아오는 모델이고 viewMain은 view에서 사용하는 모델인데, 아직 서버에서 받아오는 데이터를 안봤기 때문에 그냥 동일하게 만들어놓은 것입니다. 서버 연결하면서 정리할게요

2021-05-26 14:39 UTC, psychehose commented on MARU/MARU/Screens/Main/View/Component/Cells/MainHeaderCell.swift
> +    backImageView.adds([mypageButton,
요기까지 반영완료

2021-05-29 09:07 UTC, psychehose commented on MARU/MARU/Screens/Main/View/Component/Cells/MainHeaderCell.swift
> +      make.leading.equalTo(self.snp.leading).inset(16)
넵

2021-05-29 09:07 UTC, psychehose commented on MARU/MARU/Screens/Main/View/Component/Cells/NewMeetingCell.swift
> +    $0.image = UIImage(named: "qmarkLeft")
여긴 나중에 수정할 때 할게요. 아직 이미지 안받았어요

2021-05-29 10:45 UTC, psychehose commented on MARU/MARU/Screens/Main/View/Component/Cells/PopularMeetingCell.swift
> +      make.width.equalTo(contentView.snp.width)
superview가 contentView로 알고 있어요.

2021-05-29 10:51 UTC, merged

2021-05-29 10:52 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/PopularMeetingCell.swift
> +      make.width.equalTo(contentView.snp.width)
superView는 해당 뷰를 addSubview 한곳이 기준입니다!! 따라서 contentView에 걸게 되면 문제가 생길수도 있죠!

2021-05-29 10:53 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/Component/Cells/PopularMeetingCell.swift
> +      make.width.equalTo(contentView.snp.width)
superView는 나 자신의 superView

일반적인 UIViewController에서 superview로 생각이 많이 되기는 한데 상대적으로 생각하면 좋아요