Implement Infinite Scroll. (API 하나 바뀌는데 그거 수정하면 됨)
bookmaru/MARU-iOS pull request #80
Opened 2021-08-19 21:33 UTC by psychehose

## 종류
- [x] New Feature
- [x] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요
 메인에서 지금 새로나온 모임 화살표 넘어간 화면 페이징, 필터 구현
## 변경 사항

## 참고 사항
 전체에선 아직 무한스크롤 안됨 ( API 없음 - 전체에서 스크롤 하면 오류 뜸)

2021-08-23 02:23 UTC, 5anniversary requested changes

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Network/Model/DTO/MeetingModel.swift
>    let discussionGroupId: Int
discussionGroupID로 변경해주세요~

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Network/Router/HomeRouter.swift
> +  case getNewCategory(String, Int)
여기도 naming tuple이 좋을거같아요! 이름이 없으니깐 어떤거인지...모르겠네요

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Component/BookCell.swift
> +    bookImage = Image.testImage
label들은 text = nil로 변경해주는게 좋아요!
bookImage.image도 = nil!

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Component/MeetingListCell.swift
>    private var bookImage: UIImage! {
강제...는 지워주세요 제발...

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Component/BookCell.swift
> +    bookImage = Image.testImage
여기 파일 23라인에 UIImage도 강제로 되어있는데 강제는...진짜 안사용하면...안되겠습니까...

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Component/IndicatorFooter.swift
> +  }
UIActivityIndicatorView가 바뀌는거는 없어보이고 state만 변경되는거 같은데 variable 데이터로 가지고 있어야하나요?

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Component/MeetingListCell.swift
> +    bookImage = Image.testImage
text, image = nil

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +    }
이거 뭔가 여기저기서 사용할거같은데 ViewController 바깥으로 빼주세요

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +  private lazy var allButtons: [UIButton] = [
private var로 선언시켜준 이유가 뭐죠?

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +        self?.meetingList = $0
.drive { [weak self] in
 guard let self = self else { return } 해주면 self 뒤에 물음표를 써줄 필요가 업서요

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +    ])
button들을 다 따로 만들어줘서 복잡해진거같은데 왜 따로 만들어준건지 궁금합니다

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +      "기타"]
"종교",
"기타"
]

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +      return UICollectionReusableView() }
```swift
    guard let footer = collectionView.dequeueReusableSupplementaryView(
             ofKind: UICollectionView.elementKindSectionFooter,
             withReuseIdentifier: IndicatorFooter.reuseIdentifier,
             for: indexPath
) as? IndicatorFooter else {
       return UICollectionReusableView() 
}
```

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +    let discussionGroupId = cell.getDiscussionGroupId()
지금까지 discussionGroupId로 되어있는게 많았는데 "ID"로 잘 챙겨주세요

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Main/ViewModel/MoreNewViewModel.swift
> +      .map {$0.data?.groupsByCategory }
{ $0.data?.groupByCategory }

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Main/ViewModel/MoreNewViewModel.swift
> +      }
여기도 컨벤션에 맞지 않아보입니다...

2021-08-23 02:23 UTC, 5anniversary commented on MARU/MARU/Screens/Main/ViewModel/MoreNewViewModel.swift
> +      .map { $0.flatMap { $0 }}
이거는 왜 있죠?!

2021-08-23 02:24 UTC, 5anniversary commented
swiftlint 컨벤션에 맞지 않아보이는게 많은데 잘 챙겨주세요...

2021-08-23 03:37 UTC, psychehose commented on MARU/MARU/Network/Router/HomeRouter.swift
> +  case getNewCategory(String, Int)
밑에 task에 어차피 기입할거라 안적었는데 기입해줄게

2021-08-23 03:46 UTC, psychehose commented on MARU/MARU/Screens/Component/BookCell.swift
> +    bookImage = Image.testImage
강제를 싫어하는 건 알겠는데, 내가 이렇게 한 이유는 prepareForReuse()에서
 bookImage = UIImage() 라고 해둬서 그런거였음. nil이 절대 들어갈 수 없다고 생각해서 그렇게 했던거였어 밑에 보면 왜냐하면 bind에 catch로  bookImage에 값을 대입하니깐 무튼 수정할게

2021-08-23 03:50 UTC, psychehose commented on MARU/MARU/Screens/Component/IndicatorFooter.swift
> +  }
무슨말 하는 지 모르겠어

2021-08-23 03:53 UTC, psychehose commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +    }
Global/Enum/에 넣을게

2021-08-23 03:58 UTC, psychehose commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +  private lazy var allButtons: [UIButton] = [
UIComponent 들은 let으로 쓸게

2021-08-23 03:58 UTC, psychehose commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +        self?.meetingList = $0
아 그런 방법이 있네, 물음표 처리를 어떻게할까 계속 고민했는데

2021-08-23 03:59 UTC, psychehose commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +        self?.meetingList = $0
꿀팁 ㄱㅅㄱㅅ

2021-08-23 04:04 UTC, psychehose commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +    ])
이 뷰에 전체 카테고리에서 각 카테고리 버튼 클릭 시 필터링 해야해서 이렇게 했어. 버튼이 10개라 엄청 길긴하다

2021-08-23 04:04 UTC, psychehose commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +      "기타"]
넹

2021-08-23 04:07 UTC, psychehose commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +      return UICollectionReusableView() }
아 이거 항상 뭐가 뭔지 모르겠다

2021-08-23 04:08 UTC, psychehose commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +      return UICollectionReusableView() }
규칙을 잘 모르겠음 후후.....

2021-08-23 04:19 UTC, psychehose commented on MARU/MARU/Screens/Main/ViewModel/MoreNewViewModel.swift
> +      .map { $0.flatMap { $0 }}
서버에서 
category : Stirng
groupbycategory : [Group] 이렇게 날라오는데 (group에는 category가 없음)

meetingModel에 category 넣는 과정입니다.
저렇게 아래로 계속 내려가면 [[MeetingModel]] 이차원배열로 나오는데 flatMap을 통해 1차원 배열로 눌러준것입니다

2021-08-23 04:26 UTC, psychehose commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +    let discussionGroupId = cell.getDiscussionGroupId()
으어어어

2021-08-23 04:26 UTC, psychehose commented on MARU/MARU/Screens/Main/View/MoreNewViewController.swift
> +    let discussionGroupId = cell.getDiscussionGroupId()
반영완료..

2021-08-23 10:36 UTC, 5anniversary commented on MARU/MARU/Screens/Component/IndicatorFooter.swift
> +  }
흠 indicatorView 안의 속성값만 변경 되는데 굳이 var로 선언할 필요가 있나 했어

2021-08-23 13:02 UTC, 5anniversary approved these changes

2021-08-24 01:01 UTC, psychehose commented on MARU/MARU/Screens/Component/IndicatorFooter.swift
> +  }
너 말이 맞아 let으로 해도 되지 수정할게

2021-08-24 01:13 UTC, merged