Feature/#82
bookmaru/MARU-iOS pull request #84
Opened 2021-08-22 18:17 UTC by profitjean

## 종류
- [ ] New Feature
- [x] Change
- [x] Bug fix
- [ ] Setup (CI / CD)

## 개요
- 나의 서재 서버 연결 성공했습니다 (📡200 떴다🎉 )
- 프로필 정보 조회 서버 연결도 성공했어욥
- collectionview header 추가 코드를 변경했어요
## 변경 사항
- 담아둔 모임, 모임하고 싶은 책 받아오는 데이터 구조가 완전 다른 관계로 새로운 cell 파일을 추가해서 작업했어요
## 참고 사항
- 도움 요청🚨 
서버 연결은 돼서 한 고비 넘긴 것 같은데(_과연 그럴지_) headerview가 안 떠요. 뭔가 내가 실수한 게 있는건지 궁금🤔

2021-08-23 02:01 UTC, 5anniversary requested changes

2021-08-23 02:01 UTC, 5anniversary commented on MARU/MARU/Network/Model/DTO/BookCaseModel.swift
> +  let imageUrl: String
`imageURL`로 맞춰주세요~!

2021-08-23 02:01 UTC, 5anniversary commented on MARU/MARU/Network/Model/DTO/BookCaseModel.swift
> +  let bookcaseId: Int
여기도 bookcaseID

2021-08-23 02:01 UTC, 5anniversary commented on MARU/MARU/Network/Model/DTO/BookCaseModel.swift
> +  let groupId: Int
groupID

2021-08-23 02:01 UTC, 5anniversary commented on MARU/MARU/Network/Model/DTO/BookCaseModel.swift
> +  let meLeader: Bool
만약 이게 리더가 맞는지 아닌지 체크라는거라면 isLeader가 좋지 않을까...생각해봅니다.

2021-08-23 02:01 UTC, 5anniversary commented on MARU/MARU/Network/Model/DTO/BookCaseModel.swift
> +  let userId: Int
userID

2021-08-23 04:37 UTC, psychehose approved these changes

2021-08-23 04:37 UTC, psychehose commented on MARU/MARU/Network/Model/DTO/BookCaseModel.swift
> +  let bookcaseId: Int
슬프다 슬퍼

2021-08-23 04:37 UTC, psychehose commented on MARU/MARU/Screens/Library/MyLibraryViewModel.swift
> +        // 강제 옵셔널 처리 어떻게 해제할지 고민해야함.
guard let diary = diary else { return  } 난 이런식으로 이렇게 없애긴 하는데,

if let, ?? 뭐 이런 거 사용하면 되지 않을까 더 좋은 방법 있으면 나도 알려줘

2021-08-23 07:02 UTC, profitjean commented on MARU/MARU/Screens/Library/MyLibraryViewModel.swift
> +        // 강제 옵셔널 처리 어떻게 해제할지 고민해야함.
guard let 하니까 된다 감사감사요

2021-08-23 10:49 UTC, 5anniversary approved these changes
하나만 더 챙겨주고 머지 해주세여~

2021-08-23 10:49 UTC, 5anniversary commented on MARU/MARU/Network/Model/DTO/DiaryModel.swift
>    let diaryId: Int
요기 ID도 챙겨주세요!

2021-08-23 10:50 UTC, profitjean commented on MARU/MARU/Network/Model/DTO/DiaryModel.swift
>    let diaryId: Int
지금 콜렉션뷰 데이터 받아오는거 다시 고쳐보고 있어서 그거 좀 이따가 푸시하고 머지할게욥

2021-08-24 01:19 UTC, psychehose approved these changes

2021-08-24 08:32 UTC, merged