Implement Quiz View + Quiz Result (화면 전환은 추후에)
bookmaru/MARU-iOS pull request #88
Opened 2021-08-28 04:41 UTC by psychehose

## 종류
- [x] New Feature
- [ ] Change
- [ ] Bug fix
- [ ] Setup (CI / CD)

## 개요

## 변경 사항

## 참고 사항

2021-08-28 15:16 UTC, 5anniversary requested changes
빌드 돌려보면 Quiz 모델에서 build fail 나오는데 확인... 부탁드립니다 🙏

2021-08-28 15:16 UTC, 5anniversary commented on MARU/MARU/Network/Model/DAO/Quiz.swift
> + }
여기 뭔가 한칸 white-space가 있는거 같은데 확인 부탁드립니다 🙏

2021-08-28 15:16 UTC, 5anniversary commented on MARU/MARU/Network/Model/DAO/Quiz.swift
> + }
전체적으로 white space가 있습니다... 수정 🙏

2021-08-28 15:16 UTC, 5anniversary commented on MARU/MARU/Network/Model/DAO/Quiz.swift
> +     }
라인이 맞지 않아요... 수정...🙏

2021-08-28 15:16 UTC, 5anniversary commented on MARU/MARU/Network/Router/QuizRouter.swift
> +    return URL(string: "http://3.36.251.65:8080")!
hoxy 앞으로 환경변수의 baseURL을 사용해줄수있나요??

`Enviroment.baseURL`

2021-08-28 15:16 UTC, 5anniversary commented on MARU/MARU/Network/Model/DAO/Quiz.swift
> +
확인해보니 Quiz의 복수형은 quizzes 군요... 수정... plz 🙏

2021-08-28 15:16 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/QuizViewController.swift
> +    )
Button -> Btn 축약어 안써주시면 감사하겠습니다 🙏

2021-08-28 15:16 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/View/QuizViewController.swift
> +          print("Failure")
log 제거 부탁합니다! 🙏

2021-08-28 15:16 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/ViewModel/QuizResultViewModel.swift
> +      .withLatestFrom(input.resultValue)
여기서 withLatestFrom을 써준 이유가 궁금합니다 
viewTrigger 는 Void값인데 차라리 flatmap을 써서 resultvalue를 받는게 좋지 않나? 그런 생각...

2021-08-28 15:16 UTC, 5anniversary commented on MARU/MARU/Screens/Quiz/ViewModel/QuizResultViewModel.swift
> +      .asDriver(onErrorJustReturn: ())
그냥 input이벤트 그대로 넘겨주는거면 ViewModel에서 driver로 변환시켜줄 필요가 없지 않나요?!

2021-08-28 15:18 UTC, 5anniversary commented on MARU/MARU/Network/Router/QuizRouter.swift
> +      return .requestPlain
그냥 _만으로 처리 될거면

~~~swift
    case .getQuiz:
       return .requestPlain
     case .checkQuiz:
       return .requestPlain
~~~
의 방법이 좋아보입니다!

2021-08-29 06:15 UTC, profitjean commented
위에서 말한 것 외에는 큰 문제는 없어보임니다 ~~ 컨플릭트만 해결하고 머지해주세요

2021-08-29 14:04 UTC, psychehose commented on MARU/MARU/Screens/Quiz/ViewModel/QuizResultViewModel.swift
> +      .withLatestFrom(input.resultValue)
withLastestForm 쓴 이유는 viewTrigger는 한번 onNext 되니까 그 때 resultValue 가져오려고 쓴 거야.
flatmap 쓰는 것도 좋은 방법인 거 같아

2021-08-29 14:04 UTC, psychehose commented on MARU/MARU/Screens/Quiz/ViewModel/QuizResultViewModel.swift
> +      .asDriver(onErrorJustReturn: ())
input은 observable<Void>라서 변환을 했어

2021-08-29 14:09 UTC, merged